name: booking_client

services:
  app:
    build: .
    container_name: booking_client_dev
    restart: unless-stopped
    ports:
      - "127.0.0.1:5188:5188"
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - shared

networks:
  shared:
    external: true
